djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('users/', include('users.urls', namespace='users')),
]

marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.marketplace_views_home, name='marketplace_home_page'),
    path('list.html', views.marketplace_views_list, name='marketplace_list_items'),
    path('<int:item_id>', views.detail, name='marketplace_detail_item'),
    path('add.html', views.add, name='marketplace_add_item'),
    path('edit/<int:item_id>', views.edit, name='edit'),
    path('editted/<int:item_id>', views.edit_item, name='edit_item'),
    path('delete/<int:item_id>', views.delete, name='delete'),
    path('deleted', views.delete_item, name='delete_item'),
    path('search.html', views.search_result, name='search_result'),
    path('itemcomment/<int:item_id>', views.add_comment, name='product_add_comment'),
    path('editcomment', views.edit_comment_page, name='product_edit_comment'),
    path('deletecomment', views.delete_comment, name='product_delete_comment'),
    path('readcomment/<int:item_id>', views.read_comment, name='product_read_comment'),
    path('sorted', views.sort_by_item, name='sort_item'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register, name='create_account'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profileedit/<str:username>', views.profile_edit, name='profile_edit'),
    path('editdetails/<str:username>', views.edit_detail, name='profile_edit_detail'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
]

marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField


# Model class for storing data.
class MarketPlaceItemObject(models.Model):

    PROD_TYPE = [
        ('electronics', 'Electronics'),
        ('furnitures', 'Furnitures'),
        ('collectible_arts', 'Collectible Arts'),
        ('home_and_kitchen', 'Home & Kitchen'),
        ('miscellaneous', 'Miscellaneous')
    ]

    prod_name = models.CharField(max_length=200)
    prod_price = models.CharField(max_length=5, default='$0')
    prod_description = models.TextField(blank=True)
    prod_comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prod_seller = models.CharField(max_length=200, default='admin')
    prod_type = models.CharField(max_length=50, choices=PROD_TYPE, default='electronics')
    date_posted = models.DateTimeField(auto_now_add=True)
    img_path_1 = models.TextField(blank=True)
    img_path_2 = models.TextField(blank=True)
    img_path_3 = models.TextField(blank=True)
    img_path_4 = models.TextField(blank=True)

    def __str__(self):
        return self.prod_name

    def get_absolute_url(self):
        return reverse("marketplace:marketplace_detail_item", args=[self.id])


# Model class for storing data.
class CreateComment(models.Model):
    item = models.ForeignKey(MarketPlaceItemObject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=800)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if(self.comment):
            return self.comment[:20]
        else:
            self.user

    def get_absolute_url(self):

        if(self.id):
            return reverse("marketplace:marketplace_detail_item", args=[self.item_id])
        else:
            return reverse("users:profile", args=[self.user.username])



# credentials for regular and admin user
regular_user = {"username": "john", "password": "regular"}
admin_user = {"username": "admin", "password": "admin"}

marketplace/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from .models import MarketPlaceItemObject, CreateComment
from django.contrib import messages
from django.http import JsonResponse
from actions.models import Action
from users.models import Details
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.humanize.templatetags.humanize import naturaltime


# controller for the home view page
def marketplace_views_home(request):
    items = MarketPlaceItemObject.objects.all()

    try:
        actions = Action.objects.all().order_by('-created')

    except Action.DoesNotExist:
        actions = None
    return render(request,
                  "marketplace/views/home.html",
                  {"purchase_history": items, "sale_item": items, "new_listing": items, "actions": actions}
                  )


# controller for the list view page
def marketplace_views_list(request):
    electronic_item_detail_view = MarketPlaceItemObject.objects.order_by('id')
    return render(request,
                  "marketplace/views/list.html",
                  {"item_list": electronic_item_detail_view}
                  )


# controller for the detail view page
def detail(request, item_id):

    all_item = MarketPlaceItemObject.objects.all()

    all_comments = CreateComment.objects.filter(item_id=item_id)

    for item in all_item:
        if item.id == item_id:
            break

    return render(request,
                          "marketplace/views/detail.html",
                          {"item_detail": item, "recommendation_product": all_item, "item_comments": all_comments})


# controller to navigate to add an item
def add(request):

    if not request.session.get('username', False):
        return marketplace_views_home(request)

    if request.method == 'POST':
        product_name = request.POST.get("product_name")
        product_category = request.POST.get("product_category")
        product_description = request.POST.get("product_description")
        product_price = request.POST.get("product_price")
        img1 = "data/" + request.POST.get("item-img-1")
        img2 = "data/" + request.POST.get("item-img-2")
        img3 = "data/" + request.POST.get("item-img-3")
        img4 = "data/" + request.POST.get("item-img-4")

        user = User.objects.get(username=request.session.get("username"))

        item = MarketPlaceItemObject(
            prod_name=product_name,
            prod_price=product_price,
            prod_description=product_description,
            prod_type=product_category,
            prod_seller=user.username,
            user=user,
            date_posted=datetime.now(),
            img_path_1=img1,
            img_path_2=img2,
            img_path_3=img3,
            img_path_4=img4
        )

        item.save()

        # log the action
        action = Action(
            user=user,
            verb="added an item",
            target=item
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You have successfully added the product: %s" % item.prod_name)
        return redirect('marketplace:marketplace_detail_item', item.id)
    else:
        return render(request, "marketplace/views/add.html")


# controller to navigate to the edit item view
def edit(request, item_id):
    all_item = MarketPlaceItemObject.objects.all()
    if "username" in request.session:
        for items in all_item:
            if items.id == item_id:
                break
        return render(request, "marketplace/views/edit.html", {"item_list": items})

    else:
        return marketplace_views_home(request)


# controller to edit detail of an item
def edit_item(request, item_id):

    item = MarketPlaceItemObject.objects.get(pk=item_id)
    user = User.objects.get(username=request.session.get("username"))

    if request.method == 'POST':
        product_name = request.POST.get("product_name")
        product_category = request.POST.get("product_category")
        product_description = request.POST.get("product_description")
        product_price = request.POST.get("product_price")

        if item.prod_name != product_name:
            verb = "edited the item name to "
        elif item.prod_description != product_description:
            verb = "edited the item description to "
        else:
            verb = "edited the item detail to "

        item.prod_name = product_name
        item.prod_type = product_category
        item.prod_description = product_description
        item.prod_price = product_price
        item.save()

        # log the action
        action = Action(
            user=user,
            verb=verb,
            target=item
        )
        action.save()

        messages.add_message(request, messages.INFO,
                             "You have successfully edited the product: %s" % item.prod_name)

        return redirect('marketplace:marketplace_detail_item', item_id)
    else:
        return render(request, "marketplace/views/edit.html", {"item_list": item})


# controller to navigate to the delete an item view
def delete(request, item_id):

    item = MarketPlaceItemObject.objects.get(pk=item_id)

    if request.session['username'] == item.user.username or request.session['role'] == 'admin':

        return render(request, "marketplace/views/delete.html", {"item_list": item})

    else:
        return redirect('marketplace:marketplace_home_page')


# controller to delete an item from the list
def delete_item(request):

    if request.method == 'POST':
        item_id = request.POST.get("id")
        confirmation = request.POST.get("confirmation")
        if confirmation == 'yes':
            item = MarketPlaceItemObject.objects.get(pk=item_id)
            item_name = item.prod_name
            item.delete()

            action = Action(
                user=User.objects.get(username=request.session.get("username")),
                verb="deleted an item " + item_name,
                target=item
            )
            action.save()
            messages.add_message(request, messages.WARNING,
                                 "You have successfully deleted the product: %s" % item_name)

        return redirect('marketplace:marketplace_list_items')


# search result
def search_result(request):

    return render(request, "marketplace/views/search.html")


# Post comment
def add_comment(request, item_id):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    _newCommentList=[]
    if is_ajax and request.method == 'POST':
        _comment = request.POST.get('_comment')
        _username = request.session.get("username")
        try:
            _newComment = CreateComment(
                 comment=_comment,
                 user_id=User.objects.get(username=_username).id,
                 item_id=item_id
            )
            _newComment.save()

            action = Action(
                user=User.objects.get(username=_username),
                verb="added a new comment",
                target=_newComment
            )
            action.save()
            _newCommentList.append({"id": _newComment.id, "comment": _newComment.comment,
                                    "date": naturaltime(_newComment.created), "user": _newComment.user.username})

            return JsonResponse({'success': 'success', 'comments': _newCommentList}, status=200)
        except MarketPlaceItemObject.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid AJAX request'}, status=400)


# read comment using ajax
def read_comment(request, item_id):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == 'GET':
        try:
            if "username" in request.session:
                userID = User.objects.get(username=request.session.get("username")).id
                userRole = Details.objects.get(user_id=userID)
                role = userRole.role
            else:
                role = None

            com_object = CreateComment.objects.filter(item_id=item_id).order_by('-created')
            _comment_list = []

            for record in com_object:
                _comment_list.append({"id": record.id, "comment": record.comment,
                                      "date": naturaltime(record.created), "user": record.user.username, "role": role})

            return JsonResponse({'success': 'success', 'comments': _comment_list}, status=200)

        except CreateComment.DoesNotExist:
            return JsonResponse({'error': 'Comment not found'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid AJAX request'}, status=400)


def edit_comment_page(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == 'POST':
        comment_id = request.POST.get('_comment_id')
        updated_comment = request.POST.get('_new_comment')
        try:
            comment = CreateComment.objects.get(pk=comment_id)
            comment.comment = updated_comment
            comment.save()

            return JsonResponse({'success': 'success'}, status=200)
        except MarketPlaceItemObject.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid AJAX request'}, status=400)


# delete comment
def delete_comment(request):

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == 'POST':
        comment_id = request.POST.get('_comment_id')
        try:
            comment = CreateComment.objects.get(pk=comment_id)
            comment.delete()
            return JsonResponse({'success': 'success'}, status=200)
        except MarketPlaceItemObject.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=200)

templates/marketplace/base.html
{# base.html file to store common part of html code #}

{% load static %}
<!DOCTYPE html>
<html lang="en">

<!-- This is the head part of the html file for home page-->
<head>
    <meta charset="UTF-8">
    <title>VT MarketPlace | {% block page-title %}{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <link rel="stylesheet" href="{% static "css/global.css" %}">
    <link rel="stylesheet" href={% block page-css %} {% endblock %} >

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;1,300;1,400&display=swap" rel="stylesheet">
     <link rel="stylesheet" href="{% static "css/reset.css" %}">

    <script src={% static "JS/jquery-3.6.0.min.js" %}></script>
    <script src={% static "JS/script.js" %}></script>
</head>


<!--References-->
<!--Images and data has been taken from the Facebook MarketPlace (https://www.facebook.com/marketplace/?ref=bookmark)-->
<!--Other images have been taken from Google Images https://www.google.com/imghp?hl=en-->
<!-- Account Information icons have been taken from https://www.flaticon.com/search?word=shopping%20wishlist&type=icon-->
<!-- Virginia Tech logo has been downloaded from the website https://brand.vt.edu/identity/logo-guidelines.html-->


<!-- This is the body part of the html file for item page-->
<body>

<!-- This is the header of the all items page-->
<div class = "header">

    <!-- This is to create logo and brand name on the left side of the header-->
    <div class="title-box">
        <img src={% static "img/VT_Logo.svg" %} alt="VTLogo" height = "60" />
        <h1 id="brandName">MarketPlace</h1>
    </div>

    <!-- This is to create search bar and account related information on the right side of the header-->
    <div class="account-information">

        <!--This is to create a searchbar in the header of the page-->
        <div id = "searchBarDiv">
            <form action="search.html" method="get">
            <input type="text" id="searchBar" placeholder="Search keyboard or laptop" name = "search-items">
                <input id = "searchBarButton" type="submit" name="submit-search" value="Go">
            </form>
        </div>

        <!--This is to display cart, wishlist and profile information of the users-->

        {% if request.session.username %}

            <!--Shopping Cart-->
           <a href="#">
            <img class="menu-icon" src= {% static "img/shopping_cart_icon.svg" %} alt="Shoppingcart"  />
            </a>

            <!--Wishlist-->
            <a href="#">
            <img class="menu-icon" src= {% static "img/wishlist.png" %} alt="Wishlistlogo" />
            </a>
            <!--Account Information-->
            <a href="#" id="showUserName">
                <img class="menu-icon" src= {% static "img/profile_icon.svg" %} alt="Userprofile" />
            </a>

            <p> <a href="{% url "users:profile" request.session.username %}"> <strong> {{ request.session.username }} </strong></a> | <a href="{% url "users:logout" %}">Log out </a> </p>


        {% else %}
            <form id="loginBox" action="{% url "users:login" %}" method="POST">
                {% csrf_token %}
                <input type="text" name="username" placeholder="Username">
                <input type="password" name="password" placeholder="Password">
                <input type="submit" value="Log in"> or <a href="{% url "users:create_account" %}"> Register </a>
            </form>

        {% endif %}





    </div>
</div>

<!-- This is the primary navigation page of the all items page-->
<div class="nav-pane">
    <nav>
        {% block nav-pane-set %}
        {% endblock %}
    </nav>
</div>

<!-- This is the main content of the all items page-->
<div class="content">

{% block content-detail %}
{% endblock %}

</div>


<!-- This is the footer of the all items page -->
<div class = "footer">

    <!--left side of footer to share contact address-->
    <div class="footer-details">
        <div id="emailAddress">
            <p> Contact: <a href="#" class="link">naveengupta@vt.edu</a> </p>
        </div>

        <!--right side of footer to share other related information with respect to the website-->
        <div id="helpDocument">
            <a id="aboutUs" class="link" href="#">About Us</a>
            <a id="termsCondition" class="link" href="#">Terms & Conditions</a>
        </div>
    </div>
</div>

</body>
</html>