djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('users/', include('users.urls', namespace='users')),
]

marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.marketplace_views_home, name='marketplace_home_page'),
    path('list.html', views.marketplace_views_list, name='marketplace_list_items'),
    path('<int:item_id>', views.detail, name='marketplace_detail_item'),
    path('add.html', views.add, name='marketplace_add_item'),
    path('edit/<int:item_id>', views.edit, name='edit'),
    path('editted/<int:item_id>', views.edit_item, name='edit_item'),
    path('delete/<int:item_id>', views.delete, name='delete'),
    path('deleted', views.delete_item, name='delete_item'),
    path('search.html', views.search_result, name='search_result'),
    path('itemcomment/<int:item_id>', views.add_comment, name='product_add_comment'),
    path('editcomment', views.edit_comment_page, name='product_edit_comment'),
    path('deletecomment', views.delete_comment, name='product_delete_comment'),
    path('readcomment/<int:item_id>', views.read_comment, name='product_read_comment'),
    path('sorted', views.sort_by_item, name='sort_item'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register, name='create_account'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profileedit/<str:username>', views.profile_edit, name='profile_edit'),
    path('editdetails/<str:username>', views.edit_detail, name='profile_edit_detail'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
]

marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField


# Model class for storing data.
class MarketPlaceItemObject(models.Model):

    PROD_TYPE = [
        ('electronics', 'Electronics'),
        ('furnitures', 'Furnitures'),
        ('collectible_arts', 'Collectible Arts'),
        ('home_and_kitchen', 'Home & Kitchen'),
        ('miscellaneous', 'Miscellaneous')
    ]

    prod_name = models.CharField(max_length=200)
    prod_price = models.CharField(max_length=5, default='$0')
    prod_description = models.TextField(blank=True)
    prod_comment = models.TextField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    prod_seller = models.CharField(max_length=200, default='admin')
    prod_type = models.CharField(max_length=50, choices=PROD_TYPE, default='electronics')
    date_posted = models.DateTimeField(auto_now_add=True)
    img_path_1 = models.TextField(blank=True)
    img_path_2 = models.TextField(blank=True)
    img_path_3 = models.TextField(blank=True)
    img_path_4 = models.TextField(blank=True)

    def __str__(self):
        return self.prod_name

    def get_absolute_url(self):
        return reverse("marketplace:marketplace_detail_item", args=[self.id])


# Model class for storing data.
class CreateComment(models.Model):
    item = models.ForeignKey(MarketPlaceItemObject, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=800)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if(self.comment):
            return self.comment[:20]
        else:
            self.user

    def get_absolute_url(self):

        if(self.id):
            return reverse("marketplace:marketplace_detail_item", args=[self.item_id])
        else:
            return reverse("users:profile", args=[self.user.username])



# credentials for regular and admin user
regular_user = {"username": "john", "password": "regular"}
admin_user = {"username": "admin", "password": "admin"}

marketplace/views.py
from django.shortcuts import render, redirect
from datetime import datetime
from .models import MarketPlaceItemObject, CreateComment
from django.contrib import messages
from django.http import JsonResponse
from actions.models import Action
from users.models import Details
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib.humanize.templatetags.humanize import naturaltime


# controller for the home view page
def marketplace_views_home(request):
    items = MarketPlaceItemObject.objects.all()

    try:
        actions = Action.objects.all().order_by('-created')

    except Action.DoesNotExist:
        actions = None
    return render(request,
                  "marketplace/views/home.html",
                  {"purchase_history": items, "sale_item": items, "new_listing": items, "actions": actions}
                  )


# controller for the list view page
def marketplace_views_list(request):
    electronic_item_detail_view = MarketPlaceItemObject.objects.order_by('id')
    return render(request,
                  "marketplace/views/list.html",
                  {"item_list": electronic_item_detail_view}
                  )


# controller for the detail view page
def detail(request, item_id):

    all_item = MarketPlaceItemObject.objects.all()

    all_comments = CreateComment.objects.filter(item_id=item_id)

    for item in all_item:
        if item.id == item_id:
            break

    return render(request,
                          "marketplace/views/detail.html",
                          {"item_detail": item, "recommendation_product": all_item, "item_comments": all_comments})


# controller to navigate to add an item
def add(request):

    if not request.session.get('username', False):
        return marketplace_views_home(request)

    if request.method == 'POST':
        product_name = request.POST.get("product_name")
        product_category = request.POST.get("product_category")
        product_description = request.POST.get("product_description")
        product_price = request.POST.get("product_price")
        img1 = "data/" + request.POST.get("item-img-1")
        img2 = "data/" + request.POST.get("item-img-2")
        img3 = "data/" + request.POST.get("item-img-3")
        img4 = "data/" + request.POST.get("item-img-4")

        user = User.objects.get(username=request.session.get("username"))

        item = MarketPlaceItemObject(
            prod_name=product_name,
            prod_price=product_price,
            prod_description=product_description,
            prod_type=product_category,
            prod_seller=user.username,
            user=user,
            date_posted=datetime.now(),
            img_path_1=img1,
            img_path_2=img2,
            img_path_3=img3,
            img_path_4=img4
        )

        item.save()

        # log the action
        action = Action(
            user=user,
            verb="added an item",
            target=item
        )
        action.save()

        messages.add_message(request, messages.SUCCESS, "You have successfully added the product: %s" % item.prod_name)
        return redirect('marketplace:marketplace_detail_item', item.id)
    else:
        return render(request, "marketplace/views/add.html")


# controller to navigate to the edit item view
def edit(request, item_id):
    all_item = MarketPlaceItemObject.objects.all()
    if "username" in request.session:
        for items in all_item:
            if items.id == item_id:
                break
        return render(request, "marketplace/views/edit.html", {"item_list": items})

    else:
        return marketplace_views_home(request)


# controller to edit detail of an item
def edit_item(request, item_id):

    item = MarketPlaceItemObject.objects.get(pk=item_id)
    user = User.objects.get(username=request.session.get("username"))

    if request.method == 'POST':
        product_name = request.POST.get("product_name")
        product_category = request.POST.get("product_category")
        product_description = request.POST.get("product_description")
        product_price = request.POST.get("product_price")

        if item.prod_name != product_name:
            verb = "edited the item name to "
        elif item.prod_description != product_description:
            verb = "edited the item description to "
        else:
            verb = "edited the item detail to "

        item.prod_name = product_name
        item.prod_type = product_category
        item.prod_description = product_description
        item.prod_price = product_price
        item.save()

        # log the action
        action = Action(
            user=user,
            verb=verb,
            target=item
        )
        action.save()

        messages.add_message(request, messages.INFO,
                             "You have successfully edited the product: %s" % item.prod_name)

        return redirect('marketplace:marketplace_detail_item', item_id)
    else:
        return render(request, "marketplace/views/edit.html", {"item_list": item})


# controller to navigate to the delete an item view
def delete(request, item_id):

    item = MarketPlaceItemObject.objects.get(pk=item_id)

    if request.session['username'] == item.user.username or request.session['role'] == 'admin':

        return render(request, "marketplace/views/delete.html", {"item_list": item})

    else:
        return redirect('marketplace:marketplace_home_page')


# controller to delete an item from the list
def delete_item(request):

    if request.method == 'POST':
        item_id = request.POST.get("id")
        confirmation = request.POST.get("confirmation")
        if confirmation == 'yes':
            item = MarketPlaceItemObject.objects.get(pk=item_id)
            item_name = item.prod_name
            item.delete()

            action = Action(
                user=User.objects.get(username=request.session.get("username")),
                verb="deleted an item " + item_name,
                target=item
            )
            action.save()
            messages.add_message(request, messages.WARNING,
                                 "You have successfully deleted the product: %s" % item_name)

        return redirect('marketplace:marketplace_list_items')


# search result
def search_result(request):

    return render(request, "marketplace/views/search.html")


# Post comment
def add_comment(request, item_id):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'
    _newCommentList=[]
    if is_ajax and request.method == 'POST':
        _comment = request.POST.get('_comment')
        _username = request.session.get("username")
        try:
            _newComment = CreateComment(
                 comment=_comment,
                 user_id=User.objects.get(username=_username).id,
                 item_id=item_id
            )
            _newComment.save()

            action = Action(
                user=User.objects.get(username=_username),
                verb="added a new comment",
                target=_newComment
            )
            action.save()
            _newCommentList.append({"id": _newComment.id, "comment": _newComment.comment,
                                    "date": naturaltime(_newComment.created), "user": _newComment.user.username})

            return JsonResponse({'success': 'success', 'comments': _newCommentList}, status=200)
        except MarketPlaceItemObject.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid AJAX request'}, status=400)


# read comment using ajax
def read_comment(request, item_id):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == 'GET':
        try:
            if "username" in request.session:
                userID = User.objects.get(username=request.session.get("username")).id
                userRole = Details.objects.get(user_id=userID)
                role = userRole.role
            else:
                role = None

            com_object = CreateComment.objects.filter(item_id=item_id).order_by('-created')
            _comment_list = []

            for record in com_object:
                _comment_list.append({"id": record.id, "comment": record.comment,
                                      "date": naturaltime(record.created), "user": record.user.username, "role": role})

            return JsonResponse({'success': 'success', 'comments': _comment_list}, status=200)

        except CreateComment.DoesNotExist:
            return JsonResponse({'error': 'Comment not found'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid AJAX request'}, status=400)


def edit_comment_page(request):
    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == 'POST':
        comment_id = request.POST.get('_comment_id')
        updated_comment = request.POST.get('_new_comment')
        try:
            comment = CreateComment.objects.get(pk=comment_id)
            comment.comment = updated_comment
            comment.save()

            return JsonResponse({'success': 'success'}, status=200)
        except MarketPlaceItemObject.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=200)
    else:
        return JsonResponse({'error': 'Invalid AJAX request'}, status=400)


# delete comment
def delete_comment(request):

    is_ajax = request.headers.get('x-requested-with') == 'XMLHttpRequest'

    if is_ajax and request.method == 'POST':
        comment_id = request.POST.get('_comment_id')
        try:
            comment = CreateComment.objects.get(pk=comment_id)
            comment.delete()
            return JsonResponse({'success': 'success'}, status=200)
        except MarketPlaceItemObject.DoesNotExist:
            return JsonResponse({'error': 'Item not found'}, status=200)

templates/marketplace/views/delete.html
{# Delete view #}

{% extends "marketplace/base.html" %}
{% load static %}

{% block page-title %} Add Item {% endblock %}

{# Loading CSS #}
{% block page-css %}
    "{% static "css/add.css" %}"
{% endblock %}


{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
    <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
    <a id="sell" class="link" href={% url "marketplace:marketplace_add_item" %}>Sell</a>

{% endblock %}

{# content of the delete page view #}
{% block content-detail %}

    <div class="form-upload-item">
        <!--Add Item to List Heading-->
        <h2 id="addItem">Delete Item</h2>

        <!--To create new item in the list-->
        <form id="uploadItemToList" action="{% url "marketplace:delete_item" %}" method="post">
            {% csrf_token %}
            <!--Product Name-->
            <div class = "input-for-add">
                <label><b>Are you sure you want to delete this item?</b></label>
                <input required type="text" placeholder="yes or no" name="confirmation">
                <input type="hidden" id="id" name="id" value="{{ item_list.id }}">
            </div>

            <!--Add Item page-->
            <input id="submitButton" type="submit" value="Delete Item">

        </form>
    </div>
{% endblock %}

templates/marketplace/views/detail.html
{# Detail view to display detail of an item #}

{% extends "marketplace/base.html" %}
{% load static %}

{% block page-title %} Product Detail {% endblock %}

{# Loading the css for the page #}
{% block page-css %}
    "{% static "css/detail.css" %}"
{% endblock %}

{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    {% if request.session.username %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
        <a id="sell" class="link" href={% url "marketplace:marketplace_add_item" %}>Sell</a>

    {% else %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>

    {% endif %}

{% endblock %}

{# content of the detail page view #}
{% block content-detail %}

    {% if messages %}
        <ul class="temp-message">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {# product detail section of the page #}
    <div class="top-content">

        <!--This class is to display the multiple images of the item-->
        <div class="picture-container">
            <img src= {% static item_detail.img_path_1 %} alt="img1" class="picture-container-element" />
            <img src= {% static item_detail.img_path_2 %} alt="img1" class="picture-container-element" />
            <img src= {% static item_detail.img_path_3 %} alt="img1" class="picture-container-element" />
            <img src= {% static item_detail.img_path_4 %} alt="img1" class="picture-container-element" />
        </div>

        <!--This class is to display the item description-->
        <div class="product-description">

            <!--Product Name, details, and seller information-->
            <div class="name-and-edit">
                <h2 id="productName">{{ item_detail.prod_name }}</h2>
                 <div class="edit-button-div">
                    {% if request.session.username == item_detail.prod_seller or request.session.role == 'admin' %}
                        <a href="{% url "marketplace:edit" item_detail.id %}" class="edit-button"><img src="{% static "img/edit.png" %}"></a>
                        <a href="{% url "marketplace:delete" item_detail.id %}" class="delete-button"><img src="{% static "img/bin.png" %}"></a>
                    {% endif %}
                </div>
            </div>
            <h3 id="productUploadTime"> {{ item_detail.date_posted}} </h3>
            <p id="productTextDetail">{{ item_detail.prod_description }}</p>

            <div class="product-seller-name">
                <a href="{% url "users:profile" item_detail.user.username %}" class="link">
                    <img class = "menu-icon" src= {% static "img/email_logo.svg" %} alt="emailicon" />
                    <p> {{ item_detail.user.username }}</p>
                </a>
            </div>

            <!--Product Price-->
            <div class="product-price">
                <p id="prodPrice">{{ item_detail.prod_price }}</p>
                <p id="prodAvailability">Available</p>
            </div>

            <!--Cart Button-->
            <div class="cart-buttons">
                <button>
                    <img class="menu-icon" src={% static "img/shopping_cart_icon.svg" %} alt="Shoppingcart" />
                    Add to Cart
                </button>
                <button>
                    <img class="menu-icon" src={% static "img/wishlist.png" %} alt="Wishlistlogo" />
                    Add to Wishlist
                </button>
            </div>

        </div>
    </div>

    <!--This is the bottom half content of the page-->

    <!--Product recommendation-->

    <h3 id="recommendationHeading">Recommendations</h3>

    <div class="product-recommendation">

        {# iterating over recommended product list created in model #}
        {% for item in recommendation_product %}
            <div class="recommendations">

                <a href= {% url "marketplace:marketplace_detail_item" item.id %} class="link">
                    <img src={% static item.img_path_1 %} alt="Item1" />
                    <p class = "item-caption"> {{ item.prod_name }} {{ item.prod_price }}</p>
                </a>
            </div>
        {% endfor %}
    </div>

    <!--Product comments section-->
    <div class="product-comment">

        <!--Comment Box container-->
        <div class="comment-box">

            <!--Commented part-->
            <div class="user-commented">
                <input type="submit" data-item-id="{{ item_detail.id }}" data-user-name="{{ request.session.username }}"
                       data-ajax-url="{% url "marketplace:product_read_comment" item_detail.id %}" id="comments-recorded"
                       value="view comments">
                <div class = "comments-recorded">
                </div>
            </div>

            {% if request.session.username  %}

                <form id="prod-user-comment" action="{% url "marketplace:product_add_comment" item_detail.id %}" method="post" >
                    <!--New comment that is un-submitted-->
                    <div class="user-comment">
                        <input required type="text" placeholder="Users Comment" name = "user_new_comment" id="createUserComment">
                    </div>

                    <div>
                        <!--Add Item page-->
                        <input data-item-id="{{ item_detail.id }}" data-ajax-url="{% url "marketplace:product_add_comment" item_detail.id %}"
                               data-ajax-url2="{% url "marketplace:product_edit_comment" %}" class="submit-button" type="submit" value="comment">
                    </div>
                    {% csrf_token %}
                </form>
            {% endif %}
        </div>
    </div>


{% endblock %}

templates/marketplace/views/edit.html
{# Edit View Page #}

{% extends "marketplace/base.html" %}
{% load static %}

{% block page-title %} Add Item {% endblock %}

{# Loading CSS #}
{% block page-css %}
    "{% static "css/add.css" %}"
{% endblock %}

{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
    <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
    <a id="sell" class="link" href={% url "marketplace:marketplace_add_item" %}>Sell</a>

{% endblock %}

{# content of the edit page view #}
{% block content-detail %}

    <div class="form-upload-item">
        <!--Add Item to List Heading-->
        <h2 id="addItem">Edit Item</h2>

        <!--To create new item in the list-->
        <form id="uploadItemToList" action="{% url "marketplace:edit_item" item_list.id %}" method="post">
            {% csrf_token %}
            <!--Product Name-->
            <div class = "input-for-add">
                 <label><b> Product Name </b></label>
                <input required type="text" placeholder="Product name" name="product_name" value="{{ item_list.prod_name }}">
            </div>

            <!--Product Category-->
            <div class = "input-for-add">
                <label><b> Product Category </b></label>
                <select id="itemTypes" name="product_category">
                        <option value="Electronics">Electronics</option>
                        <option value="Furniture">Furniture</option>
                        <option value="Collectible Arts">Collectible Arts</option>
                        <option value="Home and Kitchen">Home and Kitchen</option>
                        <option value="Miscellaneous">Miscellaneous</option>
                </select>
            </div>

            <!--Product Description-->
            <div class="input-for-add">
                 <label><b> Product Description </b> </label>
                <input required type="text" placeholder="Description" name="product_description" value="{{ item_list.prod_description }}">
            </div>

            <!--Product Price-->
            <div class="input-for-add" id = "priceValidation">
                <label><b> Product Price</b></label>
                <input id = "inputPriceValidation" required type="text" placeholder="Price" name="product_price" value="{{ item_list.prod_price }}">
            </div>

            <!--Add Item page-->
            <input id="submitButton" type="submit" value="Edit Item">


        </form>
    </div>

{% endblock %}

templates/marketplace/views/list.html
{# List view to display all items. For e.g. here electronic items are displayed #}

{% extends "marketplace/base.html" %}
{% load static %}


{% block page-title %} All Items Listing {% endblock %}

{# Loading CSS #}
{% block page-css %}
    "{% static "css/list.css" %}"
{% endblock %}

{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    {% if request.session.username %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link selected" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
        <a id="sell" class="link" href={% url "marketplace:marketplace_add_item" %}>Sell</a>

    {% else %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link selected" href={% url "marketplace:marketplace_list_items" %}>All Items</a>

    {% endif %}

{% endblock %}

{% block side-tabs %}

    <li class="side-navigation">
        <a href="#" class="link selected">Electronics</a>
    </li>
    <li class="side-navigation">
        <a href="#" class="link">Furniture</a>
    </li>
    <li class="side-navigation">
        <a href="#" class="link">Collectible Art</a>
    </li>
    <li class="side-navigation">
        <a href="#" class="link">Home and Kitchen</a>
    </li>
    <li class="side-navigation">
        <a href="#" class="link">Miscellaneous</a>
    </li>
{% endblock %}

{% block side-tabs-mobile-view %}
    <!--label created to browse through item categories in mobile view-->
    <label>Select Category</label>
    <select id="itemTypes">
        <option value="Electronics">Electronics</option>
        <option value="Furniture">Furniture</option>
        <option value="Collectible Arts">Collectible Arts</option>
        <option value="Home and Kitchen">Home and Kitchen</option>
        <option value="Miscellaneous">Miscellaneous</option>
    </select>
{% endblock %}

{% block content-detail %}

    <!--Container to host the all items in the page-->
    <div class="all-item-content">

        <!--container to navigate through item categories in desktop view-->
        <div class="content-nav-pane">

            <!---Side navigation tabs to browse items of different categories-->
             <ul id="sideTabNavigation">
                <li class="side-navigation">
                    <a href="#" class="link selected">Electronics</a>
                </li>
                <li class="side-navigation">
                    <a href="#" class="link">Furniture</a>
                </li>
                <li class="side-navigation">
                    <a href="#" class="link">Collectible Art</a>
                </li>
                <li class="side-navigation">
                    <a href="#" class="link">Home and Kitchen</a>
                </li>
                <li class="side-navigation">
                    <a href="#" class="link">Miscellaneous</a>
                </li>
            </ul>
        </div>

        <!--container to navigate through item categories in mobile view-->
        <div class="content-nav-pane-mobile-view">

            <!--label created to browse through item categories in mobile view-->
            <label>Select Category</label>
            <select id="itemTypes">
                <option value="Electronics">Electronics</option>
                <option value="Furniture">Furniture</option>
                <option value="Collectible Arts">Collectible Arts</option>
                <option value="Home and Kitchen">Home and Kitchen</option>
                <option value="Miscellaneous">Miscellaneous</option>
            </select>
        </div>

        <!--This container is created to contain all the items available for sell on the website-->
        <div class="right-side-item-pane">


            {% if messages %}
                <ul class="temp-message">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <!--if the item list is empty-->
            {% if item_list.count == 0 %}
                <div class="no-item-message">
                    <h2> There are no items in the database </h2>
                </div>
            {% else %}

            <!--Filter element to sort the items-->
            <div class="filter">
                <a href="{% url "marketplace:sort_item" %}">
                     <img src= {% static "img/filter_logo.svg" %} alt="sortbyfilter" class="menu-icon" />
                     Sort by Name
                </a>

            </div>

            <!--Individual items displayed in all items page-->
            <div class="item-display">
                {% for item in item_list %}
                    <!--individual items available for sell-->
                    <div class="item-list">
                        <a href = {% url "marketplace:marketplace_detail_item" item.id %} class="link">
                            <img src= {% static item.img_path_1 %} alt="Item1" class = "individual-item-image" />
                            <p class = "item-caption">{{ item.prod_name}} {{ item.prod_price }} </p>
                        </a>
                        <div>
                            {% if request.session.role == "admin" %}
                                <a href="{% url "marketplace:edit" item.id %}" class="edit-button"><img src="{% static "img/edit.png" %}"></a>
                                <a href="{% url "marketplace:delete" item.id %}" class="delete-button"><img src="{% static "img/bin.png" %}"></a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
        {% endif %}
        </div>
    </div>
    </div>

{% endblock %}

templates/marketplace/views/search.html
{% extends "marketplace/base.html" %}
{% load static %}



{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    {% if request.session.username %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
        <a id="sell" class="link" href="add.html">Sell</a>

    {% else %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>

    {% endif %}

{% endblock %}

{% block content-detail %}

    <div class="search-result-text">
        <h2 id="searchResultHeading"> Search Results</h2>
    </div>

    <div class="search-result-content">

    </div>

{% endblock %}