djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register, name='create_account'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profileedit/<str:username>', views.profile_edit, name='profile_edit'),
    path('editdetails/<str:username>', views.edit_detail, name='profile_edit_detail'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
]

actions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey


# Create your models here.
class Action(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    verb = models.CharField(max_length=100)
    target_ct = models.ForeignKey(ContentType, blank=True, null=True, on_delete=models.CASCADE)
    target_id = models.PositiveIntegerField(blank=True, null=True)
    target = GenericForeignKey('target_ct', 'target_id')
    created = models.DateTimeField(auto_now_add=True)

actions/views.py
from django.shortcuts import render

# Create your views here.

templates/actions/action/feed.html
{% load humanize %}
{% load static %}

{# Loading CSS #}
{% block page-css %}
     <link rel="stylesheet" href="{% static "css/feed.css" %}">
{% endblock %}

<h3 class="activity-heading"> Recent Activity: </h3>
<ul class="activity-log">
    {% for action in actions %}
        {% if action.target != None or "deleted" in action.verb %}
            <li> - <a href="{% url "users:profile" action.user.username %}">{{ action.user.username}}</a> {{ action.verb }}
                {% if action.target != None %}"<a href="{{ action.target.get_absolute_url }}"> {{ action.target }} </a>" {% endif %}
                ({{ action.created|naturaltime }})
            </li>
        {% endif %}
    {% empty %}
        <li> No Activity Yet.</li>
    {% endfor %}
</ul>