djangoProject1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('marketplace/', include('marketplace.urls', namespace='marketplace')),
    path('users/', include('users.urls', namespace='users')),
]

marketplace/urls.py
from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.marketplace_views_home, name='marketplace_home_page'),
    path('list.html', views.marketplace_views_list, name='marketplace_list_items'),
    path('<int:item_id>', views.detail, name='marketplace_detail_item'),
    path('add.html', views.add, name='marketplace_add_item'),
    path('edit/<int:item_id>', views.edit, name='edit'),
    path('editted/<int:item_id>', views.edit_item, name='edit_item'),
    path('delete/<int:item_id>', views.delete, name='delete'),
    path('deleted', views.delete_item, name='delete_item'),
    path('search.html', views.search_result, name='search_result'),
    path('itemcomment/<int:item_id>', views.add_comment, name='product_add_comment'),
    path('editcomment', views.edit_comment_page, name='product_edit_comment'),
    path('deletecomment', views.delete_comment, name='product_delete_comment'),
    path('readcomment/<int:item_id>', views.read_comment, name='product_read_comment'),
    path('sorted', views.sort_by_item, name='sort_item'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register', views.register, name='create_account'),
    path('profile/<str:username>', views.profile, name='profile'),
    path('profileedit/<str:username>', views.profile_edit, name='profile_edit'),
    path('editdetails/<str:username>', views.edit_detail, name='profile_edit_detail'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse


class Details(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.CharField(default='regular', max_length=50)
    user_gender = [
        ('male', 'Male'),
        ('female', 'Female'),
        ('not shared', 'Not Shared')
    ]
    gender = models.CharField(max_length=50, choices=user_gender, default='not shared')
    profile_pic = models.TextField(blank=True)

    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse("users:profile", args=[self.user.username])


@receiver(post_save, sender=User)
def create_user_details(sender, instance, created, **kwargs):
    if created:
        Details.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_details(sender, instance, **kwargs):
    instance.details.save()

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib import messages
from actions.models import Action
from users.models import Details


# user profile controller
def profile(request, username):

    user1 = get_object_or_404(User, username=username)
    try:

        actions = Action.objects.filter(user=user1).order_by('-created')

    except Action.DoesNotExist:
        actions = None

    return render(request, "users/user/profile.html", {"user": user1, "actions": actions})


# create user account
def register(request):

    if request.method == 'POST':
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = User.objects.create_user(first_name=firstname, last_name=lastname, username=username, email=email,
                                        password=password)

        login_user(request)
        messages.add_message(request, messages.SUCCESS,
                             "Your account is successfully registered with the username: %s" % user.username)
        return redirect("marketplace:marketplace_home_page")

    return render(request,
                  "users/user/register.html")


# controller to login in the website
def login_user(request):
    username = request.POST.get("username")
    password = request.POST.get("password")

    user = authenticate(username=username, password=password)

    if user is not None:
        request.session['username'] = user.username
        request.session['role'] = user.details.role
        messages.add_message(request, messages.SUCCESS, "You have logged in successfully.")
    else:
        messages.add_message(request, messages.ERROR, "Invalid username or password.")

    return redirect('marketplace:marketplace_home_page')


# controller to logout from the website
def logout_user(request):
    del request.session['username']
    del request.session['role']
    return redirect('marketplace:marketplace_home_page')


# controller to navigate to the edit item view
def profile_edit(request, username):
    all_users = User.objects.all()
    if "username" in request.session:
        for user in all_users:
            if user.username == username:
                break
        return render(request, "users/user/profile_edit.html", {"user_list": user})

    else:
        return redirect('marketplace:marketplace_home_page')


# controller to edit detail of an item
def edit_detail(request, username):
    user1 = User.objects.get(username=request.session.get("username"))
    user = User.objects.get(username=username)

    if request.method == 'POST':
        _firstname = request.POST.get("firstname")
        _lastname = request.POST.get("lastname")
        _email = request.POST.get("email")
        _profilepicture = request.POST.get("profile-picture")
        _gender = request.POST.get("gender")
        _password = request.POST.get("password")

        role = user.details.role
        if request.session['role'] == "admin":
            _role = request.POST.get("role")
            user.details.role = _role

        user.first_name = _firstname
        user.last_name = _lastname
        user.email = _email
        if _password:
            user.set_password(_password)
        user.details.gender = _gender


        if _profilepicture != "":
            user.details.profile_pic = "profilepicture/" + _profilepicture

        user.save()
        userID = User.objects.get(username=username).id
        userProfile = Details.objects.get(user_id=userID)

        # log the change role action
        if request.session['role'] == "admin" and role != _role:
            action = Action(
                user=user1,
                verb="Changed the user role to " + _role + " for ",
                target=userProfile
            )
            action.save()
        messages.add_message(request, messages.INFO,
                             "You have successfully edited your information")

        return redirect('users:profile', user.username)
    else:
        return redirect('users:profile', user.username)

templates/users/user/profile.html
{% extends "marketplace/base.html" %}
{% load static %}

{% block page-title %} Product Detail {% endblock %}

{# Loading the css for the page #}

{% block page-css %}
    "{% static "css/profile.css" %}"
{% endblock %}

{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    {% if request.session.username %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
        <a id="sell" class="link" href={% url "marketplace:marketplace_add_item" %}>Sell</a>

    {% else %}

        <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
        <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>

    {% endif %}

{% endblock %}

{# content of the detail page view #}
{% block content-detail %}

    {% if messages %}
        <ul class="temp-message">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {# product detail section of the page #}
    <div class="top-content">

        <h2 id="profile-info">Profile Information </h2>

        {% if request.session.username == user.username or request.session.role == 'admin' %}
            <a href="{% url "users:profile_edit" user.username %}" class="edit-button"><img src="{% static "img/edit.png" %}"></a>
        {% endif %}

        <div class="profile-and-actions">
            <div class="profile-content">
                <!--This class is to display the multiple images of the item-->
                <div class="picture-container">
                    <img src= {% static user.details.profile_pic %} alt="img1" class="picture-container-element" />
                </div>

                <!--This class is to display the item description-->
                <div class="user-description">

                    <!--Profile, details, and seller information-->
                    <div class="user-detail">
                        <p class="field"> First Name: </p>
                        <p class="field-value">{{ user.first_name }}</p>
                    </div>
                     <div class="user-detail">
                        <p class="field"> Last Name: </p>
                        <p class="field-value">{{ user.last_name }}</p>
                    </div>
                     <div class="user-detail">
                        <p class="field"> Username: </p>
                        <p class="field-value">{{ user.username }}</p>
                    </div>
                     <div class="user-detail">
                        <p class="field"> Role: </p>
                        <p class="field-value">{{ user.details.role }}</p>
                    </div>
                     <div class="user-detail">
                        <p class="field"> Gender: </p>
                        <p class="field-value">{{ user.details.gender }}</p>
                    </div>
                     <div class="user-detail">
                        <p class="field"> Email Address: </p>
                        <p class="field-value">{{ user.email }}</p>
                    </div>
                </div>
            </div>

        </div>
    </div>

    {% block usersidebar %}
        {% include "actions/action/feed.html" %}
    {% endblock %}

{% endblock %}

templates/users/user/profile_edit.html
{# Edit View Page #}

{% extends "marketplace/base.html" %}
{% load static %}

{% block page-title %} Add Item {% endblock %}

{# Loading CSS #}
{% block page-css %}
    "{% static "css/profile_edit.css" %}"
{% endblock %}

{# Setting navigation pane customization for logged in and logged out users #}
{% block nav-pane-set %}

    <a id="home" class="link" href={% url "marketplace:marketplace_home_page" %}>Home</a>
    <a id="allItems" class="link" href={% url "marketplace:marketplace_list_items" %}>All Items</a>
    <a id="sell" class="link" href={% url "marketplace:marketplace_add_item" %}>Sell</a>

{% endblock %}

{# content of the edit page view #}
{% block content-detail %}

    <div class="form-edit-profile">

        <!--Add Item to List Heading-->
        <h2 id="editProfile"> Edit Profile</h2>

        <!--To create new item in the list-->
        <form id="editUserToDB" action="{% url "users:profile_edit_detail" user_list.username %}" method="post">

            <div class="user-for-edit">
                <label><b> First Name </b></label>
                <input required type="text" placeholder= "First Name" name="firstname" value="{{ user_list.first_name }}">
            </div>

            <div class="user-for-edit">
                <label><b> Last Name </b></label>
                <input required type="text" placeholder= "Last Name" name="lastname" value="{{ user_list.last_name }}">
            </div>

            <div class="user-for-edit">
                 <label><b> Email </b> </label>
                <input required type="email" placeholder="email" name="email" value="{{ user_list.email }}">
            </div>

            <div class="user-for-edit">
                <label><b>Profile Picture</b></label>
                <input id="uploadImages" type="file" name = "profile-picture" accept="image/*">
                <div id="thumbnailPreview"></div>
            </div>

            {% if request.session.role == 'admin' %}
                <div class="user-for-edit">
                     <label><b> Role </b> </label>
                    <input required type="text" placeholder="role" name="role" value="{{ user_list.details.role }}">
                </div>
            {% endif %}

            <div class="user-for-edit">
                <label><b> Gender </b> </label>
                <div class="gender-option">
                    <input id="male-gender"  required type="radio" value="Male" placeholder="Male" name="gender">
                    <label for="male-gender">Male</label><br>
                    <input id="female-gender"  required type="radio" value="Female" placeholder="Female" name="gender">
                    <label for="female-gender">Female</label><br>
                    <input id="not-share-gender" required type="radio" value="Not Share" placeholder="Not Share" name="gender">
                    <label for="not-share-gender">Not Share</label>
                </div>

            </div>

            <!--Product Price-->
            <div class="user-for-edit" id = "priceValidation">
                <label><b> Password (Optional) </b></label>
                <input type="password" placeholder="password" name="password" value="">
            </div>

            <!--Add Item page-->
            <input id="submitButton" type="submit" value="Save">

            {% csrf_token %}
        </form>
    </div>

{% endblock %}

templates/users/user/register.html
{# Add view to add an item to list. #}

{% extends "marketplace/base.html" %}
{% load static %}

{% block page-title %} Create User Account {% endblock %}

{# Loading CSS #}
{% block page-css %}
    "{% static "css/register.css" %}"
{% endblock %}

{# content of the add page view #}
{% block content-detail %}

    <div class="form-register-account">

        <!--Add Item to List Heading-->
        <h2 id="addItem"> Create an account</h2>

        <!--To create new item in the list-->
        <form id="addUserToDB" action="{% url "users:create_account" %}" method="post">

            <div class="user-for-add">
                <label><b> First Name </b></label>
                <input required type="text" placeholder= "First Name" name="firstname">
            </div>

            <div class="user-for-add">
                <label><b> Last Name </b></label>
                <input required type="text" placeholder= "Last Name" name="lastname">
            </div>

            <div class="user-for-add">
                <label><b> Username </b></label>
                <input required type="text" placeholder= "username" name="username">
            </div>


            <div class="user-for-add">
                 <label><b> Email </b> </label>
                <input required type="text" placeholder="email" name="email">
            </div>

{#            <div class="user-for-add">#}
{#                <label><b>Profile Picture</b></label>#}
{#                <input id="uploadImages" type="file" name = "profile-picture" accept="image/*">#}
{#                <div id="thumbnailPreview"></div>#}
{#            </div>#}

{#            <div class="user-for-add">#}
{#                <label><b> Gender </b> </label>#}
{#                <div class="gender-option">#}
{#                    <input id="male-gender"  required type="radio" value="Male" placeholder="Male" name="gender">#}
{#                    <label for="male-gender">Male</label><br>#}
{#                    <input id="female-gender"  required type="radio" value="Female" placeholder="Female" name="gender">#}
{#                    <label for="female-gender">Female</label><br>#}
{#                    <input id="not-share-gender" required type="radio" value="Not Share" placeholder="Not Share" name="gender">#}
{#                    <label for="not-share-gender">Not Share</label>#}
{#                </div>#}
{##}
{#            </div>#}

            <!--Product Price-->
            <div class="user-for-add" id = "priceValidation">
                <label><b> Password </b></label>
                <input required type="password" placeholder="password" name="password">
            </div>

            <!--Add Item page-->
            <input id="submitButton" type="submit" value="Create Account">

            {% csrf_token %}
        </form>
    </div>

{% endblock %}